In [1]:
import pickle
import pandas as pd
import os
import torch
import numpy as np
import torch.nn as nn
import torch.nn.functional as F

In [3]:
os.getcwd()
os.chdir(r"C:\Users\Nick\Documents\GitHub\grvmodel\Python\DATA")
dog_df = pd.DataFrame(pickle.load(open( 'dog_stats_df_FASTTRACK new margins.npy', 'rb')))
dog_df['box'] = dog_df['stats'].apply(lambda x: x[0])
dog_df = dog_df[dog_df['track_name'].str.contains("NZ")]


In [37]:
dog_df.sort_values('date')

dogid          dog_name     raceid       race_grade       date  \
997       253386773      HAPPY MEDIUM  500543142          Class 1 2019-12-01   
1007     2105690062          PAT TAMA  500543143    Class 4 Final 2019-12-01   
1008     1116480038       ALEX ATTACK  500543143    Class 4 Final 2019-12-01   
1009      141326625     DOES HE EXIST  500543143    Class 4 Final 2019-12-01   
1010      128650300        GO ALL LIN  500543143    Class 4 Final 2019-12-01   
...             ...               ...        ...              ...        ...   
1012585   471074793             DEMBE  846606735          Class 4 2022-12-01   
1012586   576143086   CALCULATED RISK  846606735          Class 4 2022-12-01   
1012587   634935932        MRS. CHINN  846606735          Class 4 2022-12-01   
1012613   537992860  HOMEBUSH SPARKLE  846606738          Class 3 2022-12-01   
1016988   515901781      OPAWA ALBERT  846624197  Mixed grade 4/5 2022-12-01   

                                                  trackOHE         track_name  \
997      [0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, ...      Auckland (NZ)   
1007     [0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, ...      Auckland (NZ)   
1008     [0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, ...      Auckland (NZ)   
1009     [0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, ...      Auckland (NZ)   
1010     [0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, ...      Auckland (NZ)   
...                                                    ...                ...   
1012585  [0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, ...  Christchurch (NZ)   
1012586  [0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, ...  Christchurch (NZ)   
1012587  [0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, ...  Christchurch (NZ)   
1012613  [0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, ...  Christchurch (NZ)   
1016988  [0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, ...       Waikato (NZ)   

          dist                                              stats  place  \
997      527.0  [8, -1, -1, -1, -1, -1, -1, -1, -1, -1, 0, 0, ...    1.0   
1007     318.0  [5, -1, -1, -1, -1, -1, -1, -1, -1, -1, 0, 0, ...    4.0   
1008     318.0  [2, -1, -1, -1, -1, -1, -1, -1, -1, -1, 0, 0, ...    3.0   
1009     318.0  [1, -1, -1, -1, -1, -1, -1, -1, -1, -1, 0, 0, ...    1.0   
1010     318.0  [3, -1, -1, -1, -1, -1, -1, -1, -1, -1, 0, 0, ...    2.0   
...        ...                                                ...    ...   
1012585  520.0  [6, 0.058408909082496435, 0.000635080027850219...    5.0   
1012586  520.0  [2, 0.05874895962279309, 0.0007828353140396463...    1.0   
1012587  520.0  [1, 0.05890329287375239, 0.0005332365673547307...    3.0   
1012613  295.0  [8, 0.05998590318052621, 0.0008156097652865078...    8.0   
1016988  457.0  [7, 0.05851138576385914, 0.0009579770498617694...    8.0   

         startprice  margin       bfSP runtime  box  
997             NaN    0.00        NaN   30.88    8  
1007            NaN    6.44        NaN   18.99    5  
1008            NaN    4.23        NaN   18.85    2  
1009            NaN    0.00        NaN   18.58    1  
1010            NaN    4.21        NaN   18.85    3  
...             ...     ...        ...     ...  ...  
1012585        11.1    6.30  10.500000   18.20    6  
1012586         9.7    0.00  10.000000   17.80    2  
1012587         6.1    2.60        NaN   17.96    1  
1012613        26.5   16.10  66.799726   18.24    8  
1016988        27.0   19.60  29.000000   26.78    7  

[111378 rows x 15 columns]

In [4]:
os.getcwd()
os.chdir(r"C:\Users\Nick\Documents\GitHub\grvmodel\Python\DATA")
dog_df_pred = pd.DataFrame(pickle.load(open( r'C:\Users\Nick\Documents\GitHub\grvmodel\Python\DATA\prediction validation 2023-01.npy', 'rb')))
dog_df_pred['box'] = dog_df_pred['stats'].apply(lambda x: x[0])
dog_df_pred = dog_df_pred[dog_df_pred['track_name'].str.contains("NZ")]


In [26]:
dog_df_pred.head(25)

dogid          dog_name     raceid race_grade       date  \
368  451768424    GOLDSTAR LINDA  853983172    Class 3 2022-12-15   
369  410839595   HOMEBUSH GLITCH  853983172    Class 3 2022-12-15   
370  550411338      SAPPORO BALE  853983172    Class 3 2022-12-15   
371  638803598  HOMEBUSH BENTLEY  853983172    Class 3 2022-12-15   
372  351419010     TAIERI TAYLEE  853983172    Class 3 2022-12-15   
373  379018103  TIGGERLONG DEMON  853983172    Class 3 2022-12-15   
374  634935922   GOLDSTAR GLENYS  853983172    Class 3 2022-12-15   
375  523685851      FREE FOR ALL  853983172    Class 3 2022-12-15   
376  534921216       ORISHA BALE  853983173  Mixed 3/4 2022-12-15   
377  476754639      ADOBE DERULO  853983173  Mixed 3/4 2022-12-15   
378  445020535     MUSTANG MEGAN  853983173  Mixed 3/4 2022-12-15   
379  638803656        SMASH WAVE  853983173  Mixed 3/4 2022-12-15   
380  779220879   DIAMOND CHIPPER  853983173  Mixed 3/4 2022-12-15   
381  775589129            MAXIMA  853983173  Mixed 3/4 2022-12-15   
382  570627038       OHOKA TOREY  853983173  Mixed 3/4 2022-12-15   
383  549372575    HOMEBUSH HONEY  853983173  Mixed 3/4 2022-12-15   
384  549372555       IT'S BETTER  853983174    Class 5 2022-12-15   
385  525211348    ALTERNATE SHOT  853983174    Class 5 2022-12-15   
386  638803648      SHANE BAXTER  853983174    Class 5 2022-12-15   
387  550411349       SMASH READY  853983174    Class 5 2022-12-15   
388  596382398       OPAWA BARNS  853983174    Class 5 2022-12-15   
389  525210837      BARBER CUBED  853983174    Class 5 2022-12-15   
390  504048112   GOLDSTAR LARSON  853983174    Class 5 2022-12-15   
391  549390088      CHATTY MAVIS  853983175    Class 3 2022-12-15   
392  540582251     SOZIN'S QUEEN  853983175    Class 3 2022-12-15   

                                              trackOHE         track_name  \
368  [0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, ...  Christchurch (NZ)   
369  [0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, ...  Christchurch (NZ)   
370  [0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, ...  Christchurch (NZ)   
371  [0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, ...  Christchurch (NZ)   
372  [0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, ...  Christchurch (NZ)   
373  [0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, ...  Christchurch (NZ)   
374  [0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, ...  Christchurch (NZ)   
375  [0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, ...  Christchurch (NZ)   
376  [0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, ...  Christchurch (NZ)   
377  [0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, ...  Christchurch (NZ)   
378  [0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, ...  Christchurch (NZ)   
379  [0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, ...  Christchurch (NZ)   
380  [0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, ...  Christchurch (NZ)   
381  [0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, ...  Christchurch (NZ)   
382  [0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, ...  Christchurch (NZ)   
383  [0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, ...  Christchurch (NZ)   
384  [0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, ...  Christchurch (NZ)   
385  [0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, ...  Christchurch (NZ)   
386  [0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, ...  Christchurch (NZ)   
387  [0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, ...  Christchurch (NZ)   
388  [0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, ...  Christchurch (NZ)   
389  [0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, ...  Christchurch (NZ)   
390  [0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, ...  Christchurch (NZ)   
391  [0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, ...  Christchurch (NZ)   
392  [0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, ...  Christchurch (NZ)   

      dist                                              stats  place  \
368  295.0  [1, 0.0581798035141873, 0.007221768971605164, ...    1.0   
369  295.0  [6, 0.05982413443430391, 0.001214426250067608,...    2.

In [23]:
dog_df_pred.dogid.value_counts().value_counts()

3    229
2    220
1    189
4    150
5     21
6      2
Name: dogid, dtype: int64

In [17]:
dog_df_pred.shape

(2033, 16)

In [15]:
dog_df_pred.raceid.value_counts().shape

(280,)

In [27]:
save_path = r"C:\Users\Nick\Documents\GitHub\grvmodel\Python\pytorch\New Model\savedmodel\test NZ GRU saver\test NZ GRU saver_450.pt"
saved_dict = torch.load(save_path)

In [30]:
# saved_dict['model_state_dict']

for param_tensor in saved_dict['model_state_dict']:
    print(param_tensor, "\t", saved_dict['model_state_dict'][param_tensor].size())

gru1.weight_ih 	 torch.Size([192, 203])
gru1.weight_hh 	 torch.Size([192, 64])
gru1.bias_ih 	 torch.Size([192])
gru1.bias_hh 	 torch.Size([192])
gru2.weight_ih 	 torch.Size([192, 203])
gru2.weight_hh 	 torch.Size([192, 64])
gru2.bias_ih 	 torch.Size([192])
gru2.bias_hh 	 torch.Size([192])
gru3.weight_ih 	 torch.Size([192, 203])
gru3.weight_hh 	 torch.Size([192, 64])
gru3.bias_ih 	 torch.Size([192])
gru3.bias_hh 	 torch.Size([192])
gru4.weight_ih 	 torch.Size([192, 203])
gru4.weight_hh 	 torch.Size([192, 64])
gru4.bias_ih 	 torch.Size([192])
gru4.bias_hh 	 torch.Size([192])
gru5.weight_ih 	 torch.Size([192, 203])
gru5.weight_hh 	 torch.Size([192, 64])
gru5.bias_ih 	 torch.Size([192])
gru5.bias_hh 	 torch.Size([192])
gru6.weight_ih 	 torch.Size([192, 203])
gru6.weight_hh 	 torch.Size([192, 64])
gru6.bias_ih 	 torch.Size([192])
gru6.bias_hh 	 torch.Size([192])
gru7.weight_ih 	 torch.Size([192, 203])
gru7.weight_hh 	 torch.Size([192, 64])
gru7.bias_ih 	 torch.Size([192])
gru7.bias_hh 	 tor

In [35]:
saved_dict['model_state_dict']['gru1.weight_ih'].shape[1]

203

In [ ]:
print(len(dog_df.trackOHE.iloc[0]),len(dog_df_pred.trackOHE.iloc[0]))
print(len(dog_df.stats.iloc[0]),len(dog_df_pred.stats.iloc[0]))

74 74
16 16


In [ ]:
dog_groups = dog_df.groupby('dogid').apply(lambda x: x.date.diff().fillna(pd.Timedelta(seconds=0))).mean()


# for i,j in dog_groups:
#     print(j.date.diff().fillna(pd.Timedelta(seconds=0)).mean())


In [ ]:
lossdf = pd.read_csv('logDFtest.csv')

In [ ]:
lossdf['count'] = 1

In [ ]:
lossdf

Unnamed: 0  actuals  preds      conf            grade  \
0              0        3      0 -1.892037          Class 1   
1              1        0      0 -1.858021    Class 4 Final   
2              2        0      1 -1.935275           Maiden   
3              3        0      1 -1.956976          Class 1   
4              4        3      1 -1.929416          Class 2   
...          ...      ...    ...       ...              ...   
1395        1395        3      1 -1.973121          Class 2   
1396        1396        7      6 -1.972819          Class 1   
1397        1397        4      0 -1.970201          Class 4   
1398        1398        2      0 -1.954375  Mixed Grade 1/2   
1399        1399        2      1 -1.883651           Maiden   

                    track  bfsps  profit  count  
0     Palmerston Nth (NZ)   -1.0     0.0      1  
1           Auckland (NZ)   -1.0     0.0      1  
2           Wanganui (NZ)   -1.0     0.0      1  
3           Wanganui (NZ)   -1.0     0.0      1  
4     Palmerston Nth (NZ)   -1.0     0.0      1  
...                   ...    ...     ...    ...  
1395    Christchurch (NZ)   -1.0     0.0      1  
1396    Christchurch (NZ)   -1.0     0.0      1  
1397    Christchurch (NZ)   -1.0     0.0      1  
1398  Palmerston Nth (NZ)   -1.0     0.0      1  
1399    Christchurch (NZ)   -1.0     0.0      1  

[1400 rows x 9 columns]

In [ ]:
lossdf['correct'] = lossdf.apply(lambda x: 1 if x['actuals']==x['preds'] else 0 , axis=1)

In [ ]:
lossdf

Unnamed: 0  actuals  preds      conf            grade  \
0              0        3      0 -1.892037          Class 1   
1              1        0      0 -1.858021    Class 4 Final   
2              2        0      1 -1.935275           Maiden   
3              3        0      1 -1.956976          Class 1   
4              4        3      1 -1.929416          Class 2   
...          ...      ...    ...       ...              ...   
1395        1395        3      1 -1.973121          Class 2   
1396        1396        7      6 -1.972819          Class 1   
1397        1397        4      0 -1.970201          Class 4   
1398        1398        2      0 -1.954375  Mixed Grade 1/2   
1399        1399        2      1 -1.883651           Maiden   

                    track  bfsps  profit  count  correct  
0     Palmerston Nth (NZ)   -1.0     0.0      1        0  
1           Auckland (NZ)   -1.0     0.0      1        1  
2           Wanganui (NZ)   -1.0     0.0      1        0  
3           Wanganui (NZ)   -1.0     0.0      1        0  
4     Palmerston Nth (NZ)   -1.0     0.0      1        0  
...                   ...    ...     ...    ...      ...  
1395    Christchurch (NZ)   -1.0     0.0      1        0  
1396    Christchurch (NZ)   -1.0     0.0      1        0  
1397    Christchurch (NZ)   -1.0     0.0      1        0  
1398  Palmerston Nth (NZ)   -1.0     0.0      1        0  
1399    Christchurch (NZ)   -1.0     0.0      1        0  

[1400 rows x 10 columns]

In [ ]:
lossdf['profit'] = lossdf.apply(lambda x: 0 if x['bfsps']<1 else x['bfsps']-1  if x['correct'] else -1, axis=1)

In [ ]:
lossdf.head(50)

In [ ]:
track_df = lossdf.groupby('track', as_index='False').sum()
track_df.reset_index()

track  Unnamed: 0  actuals  preds         conf        bfsps  \
0        Auckland (NZ)      108462      504    356  -313.361808   406.665742   
1    Christchurch (NZ)      424615     1691   1344 -1134.011454  2170.192935   
2           Otago (NZ)        2655       11      6    -3.921843     6.587735   
3  Palmerston Nth (NZ)      163765      707    527  -395.297850   707.991879   
4       Southland (NZ)       57152      277    210  -159.392282   280.675819   
5        Taranaki (NZ)         511        3      7    -3.884429    -2.000000   
6         Tokoroa (NZ)         264        6      1    -1.907290    -1.000000   
7         Waikato (NZ)      110829      498    322  -294.086931   505.410668   
8        Wanganui (NZ)      111047      701    500  -419.132124   575.837195   

        profit  count  correct      return  
0   433.665742    161       18  -52.240323  
1  2206.192935    582       79 -160.848007  
2     6.587735      2        0   -1.000000  
3   674.991879    203       15  -58.529187  
4   290.675819     82       12  -11.952603  
5     0.000000      2        1    0.000000  
6     0.000000      1        0    0.000000  
7   498.410668    151       25   -2.420617  
8   607.837195    216       34    4.400872

In [ ]:
df_pivot = dog_df.pivot(index='raceid',columns=['place'], values='margin').fillna(15)
df_pivot

ValueError: Index contains duplicate entries, cannot reshape

In [ ]:
r = torch.tensor((df_pivot.iloc[0]+1).to_list())
r

NameError: name 'df_pivot' is not defined

In [ ]:
r = torch.rand(8,10)

In [ ]:
r = r.log()
r

tensor([[-2.6411e-01, -1.3407e+00, -2.1215e+00, -1.1763e+00, -5.9946e-02,
         -1.3260e-02, -1.0272e+00, -7.4249e-01, -1.1751e-01, -2.4894e-02],
        [-1.2517e-01, -2.4667e+00, -1.0967e+00, -1.5563e+00, -1.6151e+00,
         -6.8829e-01, -4.1824e-01, -5.9266e-02, -7.7859e-02, -2.5674e-03],
        [-1.8856e-01, -6.3539e-01, -4.4113e-01, -2.4985e+00, -9.2067e-02,
         -1.4291e+00, -8.0059e-01, -5.2869e-01, -2.2559e+00, -1.2493e+00],
        [-4.5311e-01, -1.1033e+00, -4.4594e-01, -2.3675e+00, -3.7190e-01,
         -1.4691e+00, -1.0371e-01, -2.1470e+00, -1.0817e+00, -4.6440e-01],
        [-1.4361e+00, -1.1950e+00, -2.5175e-01, -9.9199e-01, -3.5735e+00,
         -5.9473e-01, -2.4475e+00, -1.4807e-04, -2.4683e-01, -2.6513e-02],
        [-2.0391e+00, -3.2843e+00, -3.9994e-01, -1.6954e-01, -4.3448e-01,
         -1.6209e+00, -5.7406e-01, -8.5910e-01, -1.6669e+00, -4.2585e-01],
        [-7.7427e-01, -3.4101e-01, -2.3569e+00, -2.4588e-02, -1.3418e+00,
         -3.8236e-01, -4.3757e-0

In [ ]:
sftmax = nn.Softmax(dim=0)
tahn = nn.Tanh()

In [ ]:
tr = tahn(r)
tr

tensor([0.0000, 0.5626, 0.7913, 0.8012, 0.8987, 0.9120, 0.9569, 0.9922])

In [ ]:
rs = torch.sigmoid(r)
rs

tensor([0.5000, 0.6540, 0.7455, 0.7506, 0.8124, 0.8233, 0.8708, 0.9412])

In [ ]:
ls = nn.LogSigmoid()
ls(r)
sftmax(-ls(r))

tensor([0.1842, 0.1408, 0.1235, 0.1227, 0.1134, 0.1119, 0.1058, 0.0978])

In [ ]:
sftmax(-rs)

tensor([0.1611, 0.1381, 0.1260, 0.1254, 0.1179, 0.1166, 0.1112, 0.1036])

In [ ]:
sftmax(-r)[0].sum()

tensor(1.2866)

In [ ]:
x = torch.rand(5,8)
y = torch.rand(5,8)

In [ ]:
cel = nn.CrossEntropyLoss(reduction='none')
kl = nn.KLDivLoss(reduction='batchmean')

In [ ]:
cel(x,y)

tensor([11.8266,  8.3206,  6.3329,  8.2975,  9.4265])

In [ ]:
x


tensor([[0.1014, 0.8791, 0.9317, 0.3059, 0.0780, 0.7030, 0.3185, 0.6284],
        [0.4854, 0.1267, 0.7048, 0.7489, 0.0646, 0.7840, 0.4067, 0.8106],
        [0.7976, 0.3691, 0.3165, 0.3107, 0.6457, 0.6709, 0.9489, 0.7234],
        [0.8811, 0.5617, 0.7810, 0.6660, 0.6791, 0.7831, 0.8993, 0.1111],
        [0.9399, 0.9951, 0.8575, 0.8524, 0.5587, 0.1212, 0.7746, 0.7384]])

In [ ]:
F.softmax(y)

C:\Users\Nick\AppData\Local\Temp\ipykernel_9188\393186831.py:1: UserWarning: Implicit dimension choice for softmax has been deprecated. Change the call to include dim=X as an argument.
  F.softmax(y)


tensor([[0.1429, 0.1112, 0.1002, 0.1097, 0.1696, 0.0995, 0.0945, 0.1724],
        [0.1079, 0.0840, 0.0814, 0.1747, 0.1592, 0.0775, 0.1444, 0.1708],
        [0.0815, 0.1318, 0.1901, 0.1068, 0.1092, 0.0899, 0.1981, 0.0926],
        [0.0909, 0.1511, 0.0941, 0.1926, 0.0840, 0.0999, 0.0827, 0.2046],
        [0.1440, 0.1322, 0.1013, 0.1525, 0.0803, 0.1262, 0.1211, 0.1424]])

In [ ]:
kl(F.log_softmax(x),F.softmax( y))

C:\Users\Nick\AppData\Local\Temp\ipykernel_9188\3956170655.py:1: UserWarning: Implicit dimension choice for log_softmax has been deprecated. Change the call to include dim=X as an argument.
  kl(F.log_softmax(x),F.softmax( y))
C:\Users\Nick\AppData\Local\Temp\ipykernel_9188\3956170655.py:1: UserWarning: Implicit dimension choice for softmax has been deprecated. Change the call to include dim=X as an argument.
  kl(F.log_softmax(x),F.softmax( y))


tensor(0.0949)

In [ ]:
torch.sum(-torch.log(torch.exp(x)/torch.sum(torch.exp(x), dim=-1, keepdim=True))*y, dim=-1)

tensor([11.8266,  8.3206,  6.3329,  8.2975,  9.4265])

In [ ]:
t = torch.tensor(0.07)

In [ ]:
torch.exp(t)

tensor(1.0725)

In [ ]:
torch.log(x+5)


tensor([[1.7389, 1.7403, 1.6914, 1.6189, 1.7836, 1.6530, 1.7834, 1.6938],
        [1.7370, 1.6225, 1.6138, 1.6427, 1.7614, 1.6542, 1.7384, 1.7578],
        [1.6402, 1.7398, 1.6300, 1.7324, 1.6566, 1.6789, 1.6379, 1.7221],
        [1.7093, 1.7366, 1.7679, 1.7428, 1.7883, 1.6988, 1.6959, 1.7411],
        [1.6652, 1.7027, 1.6596, 1.7636, 1.6534, 1.7665, 1.7050, 1.7326]])

In [ ]:
input = nn.functional.log_softmax(torch.randn(3, 5, requires_grad=True), dim=-1)
input

tensor([[-0.7779, -2.9942, -1.4254, -2.2101, -1.9628],
        [-3.9102, -4.3711, -0.1411, -3.6142, -2.6310],
        [-1.0453, -1.1885, -2.4780, -1.5419, -3.0825]],
       grad_fn=<LogSoftmaxBackward0>)

In [ ]:
x[0]

tensor([0.1014, 0.8791, 0.9317, 0.3059, 0.0780, 0.7030, 0.3185, 0.6284])

In [ ]:
torch.log_softmax(x[0], dim=0)

tensor([-2.5205, -1.7429, -1.6903, -2.3161, -2.5440, -1.9190, -2.3035, -1.9935])

In [ ]:
torch.exp(x)/torch.logsumexp(x, dim=-1, keepdim=True)

tensor([[0.4627, 0.9202, 0.4189, 0.7473, 0.7095, 0.8639, 0.4372, 0.4554],
        [0.5263, 0.9596, 0.7170, 0.5140, 0.5301, 0.4924, 0.4472, 0.6444],
        [0.3809, 0.7245, 0.9455, 0.6103, 0.9006, 0.7482, 0.9558, 0.3914],
        [0.9874, 0.5705, 0.4264, 0.9137, 0.5124, 0.9505, 0.6632, 0.3955],
        [0.6160, 0.7393, 0.4593, 0.8633, 0.3841, 0.9868, 0.5052, 0.6354]])

In [ ]:
-(y*x-torch.logsumexp(x, dim=-1, keepdim=True)*y)

tensor([[0.5153, 0.9484, 1.4135, 2.5238, 1.0821, 1.8794, 1.6698, 1.7941],
        [1.7757, 0.1372, 1.2408, 0.6135, 1.5152, 1.3158, 0.7770, 0.9455],
        [1.0113, 0.1004, 1.2988, 0.3481, 0.6725, 0.8174, 1.3157, 0.7687],
        [0.4393, 1.1434, 1.1529, 0.2367, 1.7411, 1.5715, 1.8007, 0.2119],
        [1.2393, 1.8508, 1.3630, 1.4480, 1.8165, 0.5832, 1.0275, 0.0983]])

In [ ]:
torch.mean(-(y*x-torch.logsumexp(x, dim=-1, keepdim=True)*y), dim=-1)

tensor([1.4783, 1.0401, 0.7916, 1.0372, 1.1783])

In [ ]:
yhat = torch.tensor([0.39761635661125183,
-0.12077497690916061,
-0.0892978310585022,
-0.031148605048656464,
-0.1088312640786171,
-0.1108488067984581,
-0.09906280040740967,
-0.048837367445230484
])

In [ ]:
yhat

tensor([ 0.3976, -0.1208, -0.0893, -0.0311, -0.1088, -0.1108, -0.0991, -0.0488])

In [ ]:
torch.exp(yhat)

tensor([1.4883, 0.8862, 0.9146, 0.9693, 0.8969, 0.8951, 0.9057, 0.9523])

In [ ]:
cel(yhat,yhat)

tensor(-0.6547)

In [ ]:
sftmax(torch.exp(yhat))

tensor([0.2018, 0.1105, 0.1137, 0.1201, 0.1117, 0.1115, 0.1127, 0.1181])

In [ ]:
[0.2018, 0.1105, 0.1137, 0.1201, 0.1117, 0.1115, 0.1127, 0.1181]*[-1]

TypeError: can't multiply sequence by non-int of type 'list'